name: RDP Server Deployment (Production)

on: [push, workflow_dispatch]

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 90
    permissions:
      contents: write  # Required to push connection details back to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: System Information and Prerequisites
      run: |
        echo "=== SYSTEM INFORMATION ==="
        echo "OS: $env:OS"
        echo "Processor: $env:PROCESSOR_ARCHITECTURE"
        echo "User: $env:USERNAME"
        echo "PowerShell Version: $($PSVersionTable.PSVersion)"
        echo "Current Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo "=============================="

        # Check SSH availability
        try {
          $sshVersion = ssh -V 2>&1
          echo "SSH Version: $sshVersion"
        } catch {
          echo "WARNING: SSH not found, attempting to install OpenSSH..."
          try {
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            echo "✓ OpenSSH Client installed"
          } catch {
            echo "✗ Failed to install OpenSSH: $_"
            exit 1
          }
        }

    - name: Enhanced RDP Configuration
      run: |
        echo "=== RDP CONFIGURATION ==="
        echo "Configuring Windows Remote Desktop with enhanced security..."

        try {
          # Enable Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          echo "✓ Remote Desktop enabled"

          # Configure firewall rules
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          echo "✓ Firewall rules configured"

          # Set Network Level Authentication
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          echo "✓ Network Level Authentication enabled"

          # Configure user account
          $username = "runneradmin"
          $password = "P@ssw0rd!"
          Set-LocalUser -Name $username -Password (ConvertTo-SecureString -AsPlainText $password -Force)
          echo "✓ User credentials configured"

          # Verify RDP service
          $rdpService = Get-Service -Name "TermService"
          if ($rdpService.Status -ne "Running") {
            Start-Service -Name "TermService"
            echo "✓ RDP service started"
          } else {
            echo "✓ RDP service already running"
          }

          # Check if RDP port is listening
          $rdpPort = Get-NetTCPConnection -LocalPort 3389 -ErrorAction SilentlyContinue
          if ($rdpPort) {
            echo "✓ RDP port 3389 is listening"
          } else {
            echo "⚠ RDP port 3389 not detected, but continuing..."
          }

          echo "=== RDP CONFIGURATION COMPLETE ==="

        } catch {
          echo "✗ RDP configuration failed: $_"
          echo "This may cause connection issues"
        }

    - name: Download and Setup Ngrok
      run: |
        echo "=== NGROK SETUP ==="
        echo "Downloading and configuring Ngrok..."

        try {
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip -TimeoutSec 30
          Expand-Archive ngrok.zip -DestinationPath ngrok -Force
          echo "✓ Ngrok downloaded and extracted"
        } catch {
          echo "✗ Failed to download Ngrok: $_"
          exit 1
        }

    - name: Setup Ngrok Auth
      run: |
        echo "Configuring Ngrok authentication..."
        try {
          .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          echo "✓ Ngrok authentication configured"
        } catch {
          echo "✗ Failed to configure Ngrok auth: $_"
          exit 1
        }

    - name: Create Ngrok Tunnel (Enhanced)
      run: |
        echo "=== NGROK TUNNEL SETUP ==="
        echo "Starting enhanced Ngrok tunnel..."

        # Start Ngrok tunnel with enhanced monitoring
        try {
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp", "3389", "--log=stdout" -RedirectStandardOutput "ngrok.log" -RedirectStandardError "ngrok_error.log" -NoNewWindow
          echo "✓ Ngrok process started"
        } catch {
          echo "✗ Failed to start Ngrok: $_"
          exit 1
        }

        # Wait for tunnel establishment with enhanced monitoring
        $tunnelUrl = ""
        $connectionEstablished = $false

        for ($i = 0; $i -lt 60; $i++) {
          Start-Sleep -Seconds 1

          # Try API first (most reliable)
          try {
            $response = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -Method Get -TimeoutSec 5
            $tunnel = $response.tunnels | Where-Object { $_.proto -eq "tcp" }
            if ($tunnel -and $tunnel.public_url) {
              $tunnelUrl = $tunnel.public_url
              $connectionEstablished = $true
              echo "✓ Ngrok tunnel established via API: $tunnelUrl"
              break
            }
          } catch {
            # API not ready yet, continue waiting
          }

          # Fallback to log parsing
          if (Test-Path "ngrok.log") {
            $logContent = Get-Content "ngrok.log" -Raw
            if ($logContent -match "url=tcp://([^\s\r\n]+)") {
              $tunnelUrl = "tcp://$($matches[1])"
              $connectionEstablished = $true
              echo "✓ Ngrok tunnel found in logs: $tunnelUrl"
              break
            }
          }

          if ($i % 10 -eq 0 -and $i -gt 0) {
            echo "Waiting for Ngrok tunnel... ($i/60 seconds)"
          }
        }

        if ($connectionEstablished -and $tunnelUrl) {
          $connectionDetails = @{
            host = $tunnelUrl
            username = "runneradmin"
            password = "P@ssw0rd!"
            status = "ready"
            provider = "ngrok"
            establishedAt = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
            connectionString = "mstsc /v:$($tunnelUrl -replace 'tcp://', '') /u:runneradmin"
          }

          echo "=== RDP CONNECTION DETAILS ==="
          echo "Host: $tunnelUrl"
          echo "Username: runneradmin"
          echo "Password: P@ssw0rd!"
          echo "Provider: Ngrok"
          echo "=============================="

          $jsonDetails = $connectionDetails | ConvertTo-Json -Depth 10
          $jsonDetails | Out-File -FilePath "connection-details.json" -Encoding UTF8

          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add connection-details.json
          git commit -m "Add RDP connection details [ngrok-automated]"
          git push origin main

        } else {
          echo "=== NGROK TUNNEL FAILED ==="
          echo "Failed to establish Ngrok tunnel"
          if (Test-Path "ngrok.log") {
            echo "Ngrok logs:"
            Get-Content "ngrok.log"
          }
          if (Test-Path "ngrok_error.log") {
            echo "Ngrok errors:"
            Get-Content "ngrok_error.log"
          }
          exit 1
        }
    - name: Keep RDP Server Active
      run: |
        echo "=== RDP SERVER ACTIVE ==="
        echo "RDP server is now running and accessible"
        echo "Session will remain active for the duration of this workflow"
        echo "Maximum session time: 90 minutes (GitHub Actions limit)"
        echo ""
        echo "Connection established at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo "Estimated session end: $(Get-Date -Date (Get-Date).AddMinutes(85) -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo ""
        echo "Keeping session alive..."

        # Keep alive with periodic status updates
        $startTime = Get-Date
        $maxDuration = 85 * 60  # 85 minutes in seconds
        $updateInterval = 300   # 5 minutes

        while ((Get-Date) -lt $startTime.AddSeconds($maxDuration)) {
          Start-Sleep -Seconds $updateInterval
          $elapsed = [math]::Round(((Get-Date) - $startTime).TotalMinutes, 1)
          $remaining = [math]::Round(85 - $elapsed, 1)
          echo "Session active for $elapsed minutes, $remaining minutes remaining"

          # Verify RDP service is still running
          $rdpService = Get-Service -Name "TermService" -ErrorAction SilentlyContinue
          if ($rdpService -and $rdpService.Status -eq "Running") {
            echo "✓ RDP service healthy"
          } else {
            echo "⚠ RDP service issue detected"
          }
        }

        echo "Session time limit reached, workflow ending"